apiversion: apps/v1
kind : Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app 
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  